### PR TITLE
Add some testing and solution file, also fixes AssertMeasurement only validates first qubit

### LINKED ISSUE #5: AssertMeasurement gives issues when not using on the first qubit
While adding testing in #4, seeing some differences

### PR DESCRIPTION
**Pull request by RolfHuisman**
Added some tests.

### CODE REVIEW

File: src/StabilizerProcessor.cs [hunk 1]
```diff
@@ -15,72 +15,72 @@ namespace chp
 {
     public class StabilizerProcessor : QuantumProcessorBase
     {
-        private bool[,] Table;
-        private int NQubits;
+        private readonly bool[,] table;
+        private readonly int nQubits;
```
Comment (crazy4pi314) [inline src/StabilizerProcessor.cs:19]: This would mean we can't dynamically add a qubit to the array, but with making it 1024 we are probably ok for now :P

File: src/StabilizerProcessor.cs [hunk 2]
```diff
@@ -196,22 +196,29 @@ public override void OnDumpRegister<T>(T location, IQArray<Qubit> qubits)
...
         public override Result Measure(IQArray<Pauli> bases, IQArray<Qubit> qubits)
         {
-            if (!bases.TryGetSingleZ(out var idx))
+            if (qubits.Count == 1)
             {
-                // throw new UnsupportedOperationException("Not yet implemented.");
-                var aux = this.Simulator!.QubitManager?.Allocate();
-                if (aux == null) throw new NullReferenceException("Qubit manager was null.");
-                try
+                if (!bases.HasNonZ())
```
Comment (crazy4pi314) [inline src/StabilizerProcessor.cs:201]: I don't think that these checks do the same thing as `TryGetSingleZ`, basically its looking for the "easy" case of measurement where there is only one Z pauli and the rest are identity. Then you know that the identity measurements do nothing and you can MeasureByIndex the one that has a Z. Identities are fine, its just X and Y that will need to write to scratch.

File: src/StabilizerProcessor.cs [hunk 3]
```diff
@@ -233,7 +240,7 @@ private void WriteToScratch(IQArray<Pauli> bases, IQArray<Qubit> qubits, Qubit a
                         H(qubit);
                         S(qubit);
                         ControlledX(new QArray<Qubit>(new[] { qubit }), aux);
-                        S(qubit);
+                        SAdjoint(qubit);
```
Comment (crazy4pi314) [inline src/StabilizerProcessor.cs:243]: This totally was the problem I think!

**Review by crazy4pi314 — APPROVED** [review]
I think you found it with the SAdj in the write to scratch. I want to add another multi qubit measurement test to see if this still supports all the measuements it should  (multi qubit measurements for arbitrary measurement operators/bases).

File: src/StabilizerProcessor.cs (hunk 2 above)
Comment (RolfHuisman) [reply src/StabilizerProcessor.cs:201]: Hmmm.. MeasureOneTest gave that the original TryGetSingleZ, gave index 0 back, when asserting qubit index 1, which is the first Z. But because idx was 0, it measuring qubit 0... so... it needs some additional work then.

File: src/StabilizerProcessor.cs (hunk 1 above)
Comment (RolfHuisman) [reply src/StabilizerProcessor.cs:19]: Yes, for now, untill we make it autosizing.

File: src/StabilizerProcessor.cs (hunk 3 above)
Comment (RolfHuisman) [reply src/StabilizerProcessor.cs:243]: It was one of the problems. When I fixed that one, I thought I had it. But a lot of tests kept failing.
